import type { Metadata } from "next";
import { EdgeStoreProvider } from "../lib/edgestore";
import "./globals.css";

export const metadata: Metadata = {
  title: "Antion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <EdgeStoreProvider>{children}</EdgeStoreProvider>
      </body>
    </html>
  );
}
